name: Java CI with maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
      contents: write
      packages: write
      
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        #server-id: github
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode deploy 
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

